import type { Ensemble, Student } from './types';

/**
 * 2025-26 baseline roster (from the director's spreadsheet export).
 * Same conventions as seedData.ts: stable slug ids, idempotent import.
 * Ensemble memberships are PROVISIONAL, auto-assigned by instrument per
 * the director's mapping (strings/harp/piano -> the three orchestras;
 * winds/brass/percussion/harp/piano -> Wind Ensemble; sax/piano -> Jazz).
 * Contact details are intentionally NOT in this file (auth-only Firestore
 * collection; imported separately, never committed).
 */

/** Added if missing on reset - named by the director in the July 2026 redesign kickoff. */
export const baselineNewEnsembles: Ensemble[] = [
  { id: 'philharmonic', name: 'Philharmonic', order: 9 },
];

export const baselineStudents: Student[] = [
  { id: 'aboukheirjimen-fouad-e',   name: 'Aboukheirjimen, Fouad E.',   instrument: 'Trombone',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'antia-david-d',            name: 'Antia, David D.',            instrument: 'Trumpet',   grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'asse-alias-l',             name: 'Asse, Alias L.',             instrument: 'Tuba',      grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'balding-zachary-r',        name: 'Balding, Zachary R.',        instrument: 'Trumpet',   grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'barboza-gabriel-a',        name: 'Barboza, Gabriel A.',        instrument: 'Trombone',  grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'bell-anthony-j',           name: 'Bell, Anthony J.',           instrument: 'Saxophone', grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble', 'jazz-ensemble'] },
  { id: 'berndt-katheryn-v',        name: 'Berndt, Katheryn V.',        instrument: 'Trombone',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'block-emily-m',            name: 'Block, Emily M.',            instrument: 'Violin',    grade: '10th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'bruner-pearson-a',         name: 'Bruner, Pearson A.',         instrument: 'Cello',     grade: '10th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'caballero-leonel-d',       name: 'Caballero, Leonel D.',       instrument: 'Percussion',grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'caballero-uriel-n',        name: 'Caballero, Uriel N.',        instrument: 'Bass',      grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'cabrera-cristian',         name: 'Cabrera, Cristian',          instrument: 'Trombone',  grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'caraisco-kadence-i',       name: 'Caraisco, Kadence I.',       instrument: 'Flute',     grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'carrillo-flavio-a',        name: 'Carrillo, Flavio A.',        instrument: 'Trombone',  grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'cerra-angel-s',            name: 'Cerra, Angel S.',            instrument: 'Percussion',grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'chan-ryu-s',               name: 'Chan, Ryu S.',               instrument: 'Horn',      grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'chander-isabella-c',       name: 'Chander, Isabella C.',       instrument: 'Violin',    grade: '10th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'cuneo-olympia-s',          name: 'Cuneo, Olympia S.',          instrument: 'Violin',    grade: '11th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'dawson-rachel-w',          name: 'Dawson, Rachel W.',          instrument: 'Cello',     grade: '11th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'druckerman-webber-d',      name: 'Druckerman, Webber D.',      instrument: 'Piano',     grade: '10th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic', 'wind-ensemble', 'jazz-ensemble'] },
  { id: 'fernandez-andy-w',         name: 'Fernandez, Andy W.',         instrument: 'Trombone',  grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'fortier-miley-s',          name: 'Fortier, Miley S.',          instrument: 'Clarinet',  grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'gaviria-wyatt-a',          name: 'Gaviria, Wyatt A.',          instrument: 'Saxophone', grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble', 'jazz-ensemble'] },
  { id: 'gonzalez-lincoln-r',       name: 'Gonzalez, Lincoln R.',       instrument: 'Piano',     grade: '12th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic', 'wind-ensemble', 'jazz-ensemble'] },
  { id: 'gonzalez-star-a',          name: 'Gonzalez, Star A.',          instrument: 'Flute',     grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'green-piper-k',            name: 'Green, Piper K.',            instrument: 'Tuba',      grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'guerra-rebecca-h',         name: 'Guerra, Rebecca H.',         instrument: 'Euphonium', grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'hillman-adelaide-l',       name: 'Hillman, Adelaide L.',       instrument: 'Bass',      grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'hoover-sebastian-m',       name: 'Hoover, Sebastian M.',       instrument: 'Percussion',grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'jacobs-caleb-a',           name: 'Jacobs, Caleb A.',           instrument: 'Clarinet',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'jacobs-eitan-s',           name: 'Jacobs, Eitan S.',           instrument: 'Oboe',      grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'jean-irvin-a',             name: 'Jean, Irvin A.',             instrument: 'Trumpet',   grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'jordan-tahlia-n',          name: 'Jordan, Tahlia N.',          instrument: 'Violin',    grade: '11th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'jubert-elijah-j',          name: 'Jubert, Elijah J.',          instrument: 'Saxophone', grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble', 'jazz-ensemble'] },
  { id: 'leyva-elisabet',           name: 'Leyva, Elisabet',            instrument: 'Flute',     grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'leyva-juan-c',             name: 'Leyva, Juan C.',             instrument: 'Saxophone', grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble', 'jazz-ensemble'] },
  { id: 'longa-sofia',              name: 'Longa, Sofia',               instrument: 'Bass',      grade: '12th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'maldonado-kenlie-d',       name: 'Maldonado, Kenlie D.',       instrument: 'Clarinet',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'maldonado-roulen-l',       name: 'Maldonado, Roulen L.',       instrument: 'Trumpet',   grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'mancebo-laura',            name: 'Mancebo, Laura',             instrument: 'Horn',      grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'mantilla-mateo-s',         name: 'Mantilla, Mateo S.',         instrument: 'Trombone',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'maroudas-george-p',        name: 'Maroudas, George P.',        instrument: 'Cello',     grade: '12th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'marques-veronica-l',       name: 'Marques, Veronica L.',       instrument: 'Percussion',grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'marquez-ariana-e',         name: 'Marquez, Ariana E.',         instrument: 'Bass',      grade: '12th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'marrero-catalina',         name: 'Marrero, Catalina',          instrument: 'Violin',    grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'mercado-valentina',        name: 'Mercado, Valentina',         instrument: 'Cello',     grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'morales-seth-n',           name: 'Morales, Seth N.',           instrument: 'Bassoon',   grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'naimlindenfeld-jonathan-j',name: 'Naimlindenfeld, Jonathan J.',instrument: 'Bass',      grade: '10th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'neitlich-willow-j',        name: 'Neitlich, Willow J.',        instrument: 'Harp',      grade: '10th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic', 'wind-ensemble'] },
  { id: 'neuman-haley-d',           name: 'Neuman, Haley D.',           instrument: 'Viola',     grade: '12th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'olivas-samuel-j',          name: 'Olivas, Samuel J.',          instrument: 'Horn',      grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'palma-victoria',           name: 'Palma, Victoria',            instrument: 'Bass',      grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'paz-isabella',             name: 'Paz, Isabella',              instrument: 'Clarinet',  grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'perez-blunden-kalel-l',    name: 'Perez-Blunden, Kalel L.',    instrument: 'Trombone',  grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'perezdiaz-ailin',          name: 'Perezdiaz, Ailin',           instrument: 'Percussion',grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'pierre-joselme-g',         name: 'Pierre, Joselme G.',         instrument: 'Clarinet',  grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'pierre-madeleine-s',       name: 'Pierre, Madeleine S.',       instrument: 'Cello',     grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'powell-ethan-w',           name: 'Powell, Ethan W.',           instrument: 'Saxophone', grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble', 'jazz-ensemble'] },
  { id: 'puente-gianmarco',         name: 'Puente, Gianmarco',          instrument: 'Horn',      grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'ramirez-alex-a',           name: 'Ramirez, Alex A.',           instrument: 'Saxophone', grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble', 'jazz-ensemble'] },
  { id: 'ramirez-alexander',        name: 'Ramirez, Alexander',         instrument: 'Trombone',  grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'ramirez-christophe',       name: 'Ramirez, Christophe',        instrument: 'Clarinet',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'rey-jayson',               name: 'Rey, Jayson',                instrument: 'Clarinet',  grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'riggio-benjamin',          name: 'Riggio, Benjamin',           instrument: 'Saxophone', grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble', 'jazz-ensemble'] },
  { id: 'rojas-danna-f',            name: 'Rojas, Danna F.',            instrument: 'Violin',    grade: '12th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'roman-trent',              name: 'Roman, Trent',               instrument: 'Trombone',  grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'rothenberg-sam-a',         name: 'Rothenberg, Sam A.',         instrument: 'Trumpet',   grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'sanchez-gisella-m',        name: 'Sanchez, Gisella M.',        instrument: 'Trumpet',   grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'sanchezyumbla-daniel-a',   name: 'Sanchezyumbla, Daniel A.',   instrument: 'Clarinet',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'scavuzzo-sabella-t',       name: 'Scavuzzo, Sabella T.',       instrument: 'Violin',    grade: '11th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'sendra-pierre',            name: 'Sendra, Pierre',             instrument: 'Trumpet',   grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'sirulnik-damian-r',        name: 'Sirulnik, Damian R.',        instrument: 'Bass',      grade: '11th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'szymanski-anastasia',      name: 'Szymanski, Anastasia',       instrument: 'Violin',    grade: '11th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'torres-ariel',             name: 'Torres, Ariel',              instrument: 'Trombone',  grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'torres-axel',              name: 'Torres, Axel',               instrument: 'Trumpet',   grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'tortor-chermaine-r',       name: 'Tortor, Chermaine R.',       instrument: 'Percussion',grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'toscano-carlos-e',         name: 'Toscano, Carlos E.',         instrument: 'Trumpet',   grade: '9th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'ulloa-andre-j',            name: 'Ulloa, Andre J.',            instrument: 'Clarinet',  grade: '11th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'valencia-leah-c',          name: 'Valencia, Leah C.',          instrument: 'Cello',     grade: '11th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'velasco-joseanny-k',       name: 'Velasco, Joseanny K.',       instrument: 'Bassoon',   grade: '12th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'velazco-emily-s',          name: 'Velazco, Emily S.',          instrument: 'Violin',    grade: '12th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'velazco-isabella-v',       name: 'Velazco, Isabella V.',       instrument: 'Violin',    grade: '10th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'veliz-diego-a',            name: 'Veliz, Diego A.',            instrument: 'Viola',     grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'verde-lucas-a',            name: 'Verde, Lucas A.',            instrument: 'Clarinet',  grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
  { id: 'wild-ava-s',               name: 'Wild, Ava S.',               instrument: 'Violin',    grade: '9th', status: 'Active', ensembleIds: ['camerata-string-orchestra', 'symphony-orchestra', 'philharmonic'] },
  { id: 'williams-joshua-a',        name: 'Williams, Joshua A.',        instrument: 'Trumpet',   grade: '10th', status: 'Active', ensembleIds: ['wind-ensemble'] },
];
